# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30)),
                ('c_desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
