# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('s_num', models.CharField(max_length=30)),
                ('s_username', models.CharField(max_length=30, null=True)),
                ('s_password', models.CharField(max_length=256, null=True)),
                ('c', models.ManyToManyField(blank=True, null=True, to='course.Course')),
                ('g', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.Grade')),
                ('m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.Major')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
