# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-19 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Student')),
            ],
            options={
                'db_table': 'scores',
            },
        ),
    ]
