# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_mainshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassUtilsTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_times', models.IntegerField(default=0, max_length=1)),
            ],
            options={
                'db_table': 'pass_utils_times',
            },
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='priductlongname',
            new_name='productlongname',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='u_ticket',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_id', to='index.Goods'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='index.UserModel'),
        ),
        migrations.AlterModelTable(
            name='goods',
            table='axf_goods',
        ),
        migrations.AlterModelTable(
            name='ordermodel',
            table='axf_order',
        ),
    ]
